# Supabase project configuration file

[api]
# Port to use for the local API URL
port = 54321
# Schemas to expose in your API
schemas = ["public", "storage", "graphql_public"]

[db]
# Port to use for the local database URL
port = 54322
# The database major version to use
major_version = 15

[studio]
# Port to use for the Studio URL
port = 54323

[inbucket]
# Port to use for the Inbucket URL
port = 54324

[storage]
# The maximum file size allowed (e.g. "5MB", "500KB")
file_size_limit = "50MiB"

[auth]
# The base URL of your website
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds
jwt_expiry = 3600
# Allow/disallow new user signups to your project
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in
enable_confirmations = false
